name: CI/CD Pipeline for NestJS
# test

on:
  push:
    branches:
      - master  # Pipeline akan berjalan saat ada push ke branch "master"
  pull_request:
    branches:
      - master  # Pipeline juga akan berjalan pada pull request ke branch "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (versi 20)
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Cache Node.js modules untuk mempercepat proses instalasi dependensi
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies dengan fallback ke npm install
      - name: Install dependencies
        run: |
          echo "Running npm ci..."
          npm ci || (echo "npm ci failed, falling back to npm install..." && npm install)

      # Step 5: Build project
      - name: Build the project
        run: |
          npm run build

      # Step 6: Deploy dan Restart PM2 di server
      - name: Deploy to Server and Restart PM2
        env:
          HOST: ${{ secrets.SERVER_HOST }}       # Secret yang berisi IP atau domain server
          USER: ${{ secrets.SERVER_USER }}       # Secret yang berisi username server
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Secret yang berisi private SSH key
        run: |
          echo "Deploying to server..."
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude node_modules ./ $USER@$HOST:/home/fajrulichsan/mathbot-backend

          echo "Restarting PM2..."
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY $USER@$HOST 'cd /home/fajrulichsan/mathbot-backend && npm install && pm2 restart mathbot-backend'
